### ISSUE TITLE
Parser error with Ascio

### ISSUE THREAD

**Issue by skelkelos** [weppos/whois#479] opened 2015-12-01 05:03 UTC
Unknown registrar format `Ascio Technologies, Inc. Danmark - Filial af Ascio technologies, Inc. USA' Please report the issue at http://github.com/weppos/whois/issues

For testing: 0-2.info

**Comment by weppos** [comment] 2015-12-01 23:07
Duplicate of https://github.com/weppos/whois/issues/481

**Closed by weppos** 2015-12-01 23:07 UTC
Labels: parser
