### ISSUE TITLE
Problem in parsing some domains 

### ISSUE THREAD

**Issue by safouen** [weppos/whois#380] opened 2014-12-08 16:15 UTC
I have found that there is some domains that return special characters and that causes a problem in parsing the result like "atb.com.tn"

An other question RoboWhois will close its API on January 1st, 2015, will this gem keep going on ?

**Comment by weppos** [comment] 2015-11-30 13:20
Closing as a duplicate of #11

**Closed by weppos** 2015-11-30 13:20 UTC
