### ISSUE TITLE
Parser error with Blue Razor Domains

### ISSUE THREAD

**Issue by skelkelos** [weppos/whois#488] opened 2015-12-01 05:12 UTC
Unknown registrar format `Blue Razor Domains, LLC' Please report the issue at http://github.com/weppos/whois/issues

For testing: 0-7.info

**Comment by weppos** [comment] 2015-12-01 23:05
Duplicate of https://github.com/weppos/whois/issues/481

**Closed by weppos** 2015-12-01 23:05 UTC
Labels: parser
