### ISSUE TITLE
Parser error with PSI-USA

### ISSUE THREAD

**Issue by skelkelos** [weppos/whois#485] opened 2015-12-01 05:10 UTC
Unknown registrar format `PSI-USA, Inc. dba Domain Robot' Please report the issue at http://github.com/weppos/whois/issues

For testing: 0-energiehaus.info

**Comment by weppos** [comment] 2015-12-01 23:05
Duplicate of https://github.com/weppos/whois/issues/481

**Closed by weppos** 2015-12-01 23:05 UTC
