### ISSUE TITLE
Feature: Support for properties from IP lookup.

### ISSUE THREAD

**Issue by martin-schmidt** [weppos/whois#450] opened 2015-11-06 14:55 UTC
`whois` does not support parsing of IP lookup properties. 

```ruby
record = client.lookup('5.9.232.64')
record.properties
=> {:disclaimer=>nil,
 :domain=>nil,
 :domain_id=>nil,
 :status=>:registered,
 :available?=>false,
 :registered?=>true,
 :created_on=>nil,
 :updated_on=>nil,
 :expires_on=>nil,
 :registrar=>nil,
 :registrant_contacts=>nil,
 :admin_contacts=>nil,
 :technical_contacts=>nil,
 :nameservers=>[]}
```

**Comment by weppos** [comment] 2015-11-06 15:23
Duplicate of #292

**Closed by weppos** 2015-11-06 15:23 UTC
