### ISSUE TITLE
Parser error with REGISTER.IT

### ISSUE THREAD

**Issue by skelkelos** [weppos/whois#482] opened 2015-12-01 05:08 UTC
Unknown registrar format `REGISTER.IT SPA' Please report the issue at http://github.com/weppos/whois/issues

For testing: 0-limits.info

**Comment by weppos** [comment] 2015-12-01 23:06
Duplicate of https://github.com/weppos/whois/issues/481

**Closed by weppos** 2015-12-01 23:06 UTC
Labels: parser
