### ISSUE TITLE
Parser error with GMO

### ISSUE THREAD

**Issue by skelkelos** [weppos/whois#478] opened 2015-12-01 05:02 UTC
Unknown registrar format `GMO Internet, Inc. d/b/a Onamae.com' Please report the issue at http://github.com/weppos/whois/issues

For testing: 0-1-0-7friend-333.info

**Comment by weppos** [comment] 2015-12-01 23:07
Duplicate of https://github.com/weppos/whois/issues/481

**Closed by weppos** 2015-12-01 23:07 UTC
Labels: parser
